name: Java Tests with Gradle

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 19
        distribution: 'adopt'

    - name: Build with Gradle
      working-directory: C:\Users\linus\OneDrive\Skrivbord\Java Nacka\Projekt skolan\tddgroup\TDD-Uppgift-Grupp3\tdd-group3\group-tdd-3
      run: ./gradlew test
